# fly.toml app configuration file generated for mls-grpc on 2025-05-12T20:13:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mls-grpc'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 50051
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500
  [[http_service.tls_options]]
    alpn = ["h2"]

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  auto_start_machines = true
  memory_mb = 1024