name: Buf Push

on:
  push:
    branches: [ main ]
    paths:
      - 'proto/**'
      - 'buf.yaml'
  workflow_run:
    workflows: ["RPC Tests"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

jobs:
  push-to-buf:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Buf CLI
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint proto files
        uses: bufbuild/buf-lint-action@v1

      - name: Push to Buf Schema Registry
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref != 'refs/heads/main' }} 